version: "3.3"

services:
  postgres:
    restart: unless-stopped
    image: postgres
    container_name: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: server/docker/drf.dockerfile
    image: django-skeleton:v1
    env_file:
      - ./server/.env
    container_name: ${APP_CONTAINER_NAME}
    hostname: ${APP_CONTAINER_NAME}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "${APP_PORT}:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  react:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=true

volumes:
  postgres: