# Generated by Django 4.0 on 2022-11-04 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=30)),
                ('author', models.CharField(help_text='Username', max_length=50)),
                ('location', models.JSONField()),
                ('post_date_time', models.DateTimeField()),
                ('pet_date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.IntegerField(blank=True)),
                ('tags', models.JSONField(blank=True)),
                ('reward', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('location', models.JSONField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.IntegerField()),
                ('tags', models.JSONField(blank=True)),
                ('reward', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Task description', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('photo', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=1000)),
                ('if_primary', models.BooleanField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfind.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=30)),
                ('author', models.CharField(help_text='Username', max_length=50)),
                ('location', models.JSONField()),
                ('post_date_time', models.DateTimeField()),
                ('pet_date_time', models.DateTimeField(blank=True)),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('photo', models.CharField(max_length=1000)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfind.posts')),
            ],
        ),
    ]
