# Generated by Django 4.0 on 2022-11-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pet_date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
