# Generated by Django 4.0 on 2022-11-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=30)),
                ('author', models.CharField(help_text='Username', max_length=50)),
                ('location', models.JSONField()),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.IntegerField()),
                ('tags', models.JSONField(blank=True)),
                ('reward', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=30)),
                ('author', models.CharField(help_text='Username', max_length=50)),
                ('location', models.JSONField()),
                ('date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', models.IntegerField()),
                ('tags', models.JSONField(blank=True)),
                ('reward', models.JSONField(blank=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfind.posts')),
            ],
        ),
    ]
