# Generated by Django 4.0 on 2022-11-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0002_alter_posts_pet_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
