# Generated by Django 4.0 on 2022-11-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0003_alter_comments_id_alter_comments_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shelters',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='shelters',
            name='tags',
        ),
        migrations.AlterField(
            model_name='comments',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='post_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
