# Generated by Django 4.0 on 2022-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0004_remove_comments_title_remove_shelters_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(blank=True, help_text='Username', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pet_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='reward',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, help_text='Post title', max_length=30, null=True),
        ),
    ]
