# Generated by Django 4.0 on 2022-11-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0005_alter_location_latitude_alter_location_longtitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, help_text='Username', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pet_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='photo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
