# Generated by Django 4.0 on 2022-11-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfind', '0006_posts_photo_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtitude',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
